@baseUrl = https://8080-cabreraluca-apimodelop2-sx76ccbycw7.ws-us110.gitpod.io

###
POST {{baseUrl}}/auth
Content-Type: application/json

{
    "nomeDeUsuario": "Lucas",
    "senha": "123456"
}

//docker exec -it mysql mysql -uroot -p