@baseUrl = https://8080-cabreraluca-apimodelop2-ezpwl47psow.ws-us110.gitpod.io

###
GET {{baseUrl}}/opcoes

###
POST {{baseUrl}}/opcoes
Content-Type: application/json

{
    "descricao" : "Opção 4",
    "correto": true,
    "questao" : {"id" : 1}
}